inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
  - utils:fix

ignore-paths:
  - jsonschema_validator/json_schema.py

mypy:
  options:
    python-version: '3.10'

ruff:
  options:
    target-version: py310
