[tool.black]
line-length = 110
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 110

[tool.mypy]
python_version = "3.9"
warn_redundant_casts = true
warn_unused_ignores = true
ignore_missing_imports = true
strict = true

[tool.poetry]
name = "jsonschema-validator-new"
version = "0.0.0"
description = "Tool to validate files against a JSON Schema"
readme = "README.md"
authors = ["Stéphane Brunner <stephane.brunner@gmail.com>"]
repository = "https://github.com/sbrunner/jsonschema-validator"
license = "BSD-2-Clause"
keywords = ["jsonschema", "types"]
packages = [{ include = "jsonschema_validator" }]
include = ["jsonschema_validators/py.typed"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Topic :: Software Development :: Code Generators",
    "Typing :: Typed",
]

[tool.poetry.scripts]
jsonschema-validator = "jsonschema_validator:main"

[tool.poetry.dependencies]
python = ">=3.9,<4"
jsonschema = "4.22.0"
requests = "2.32.3"
"ruamel.yaml" = "0.18.6"

[tool.poetry.dev-dependencies]
prospector = { extras = ["with_mypy", "with_bandit", "with_pyroma"], version = "1.10.3" }
pytest = "8.2.0"
pytest-cov = "5.0.0"
types-requests = "2.32.0.20240523"
types-pyyaml = "6.0.12.20240311"

[tool.poetry.group.dev.dependencies]
prospector-profile-duplicated = "1.5.0"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning", "poetry-plugin-tweak-dependencies-version", "poetry-plugin-drop-python-upper-constraint"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern = "^(?P<base>\\d+(\\.\\d+)*)"
format-jinja = """
{%- if env.get("VERSION_TYPE") == "version_branch" -%}
{{serialize_pep440(bump_version(base, 1 if env.get("IS_MASTER") == "TRUE" else 2), dev=distance)}}
{%- elif distance == 0 -%}
{{serialize_pep440(base)}}
{%- else -%}
{{serialize_pep440(bump_version(base), dev=distance)}}
{%- endif -%}
"""

[tool.poetry-plugin-tweak-dependencies-version]
default = "present"
