name: Clean Docker hub tags

on: delete

jobs:
  clean:
    runs-on: ubuntu-22.04
    name: Clean Docker hub tags
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Clean Docker hub tags
        run: c2cciutils-clean
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
